### ISSUE TITLE
Group's Stopwatch Icon/Logo

### ISSUE THREAD

**Issue by StephenMontenid** [StephenMontenid/EEE100_PROJECT#10]
Hello guys, I want to suggest, how about we create our logo that will also serve as an icon that will embody our group's project? Any thoughts?

**Comment by MarcPaulBugna** [comment]
I think I have an idea

**Comment by StephenMontenid** [comment]
> I think I have an idea

Nicee, sige marc. Ilapag mo lang dito.

**Comment by MarcPaulBugna** [comment]
![image](https://user-images.githubusercontent.com/105411431/170022139-02200df5-09fa-4667-9bbe-27af072ef4b3.png)
![image](https://user-images.githubusercontent.com/105411431/170022165-a49ecdb2-6549-4e26-bbba-72641d34dc58.png)
https://scontent.fcgy2-1.fna.fbcdn.net/v/t1.15752-9/281410185_304482961747833_775348646829113251_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=ae9488&_nc_eui2=AeH8XpF7uIzzyLjJS9F4obIUHjdb4JGDY6UeN1vgkYNjpScB-b7R0KiiGva2857UcndPXGr2yIEyCUEtSolkSJ_G&_nc_ohc=MkJ2v0g9F78AX8fSOjW&tn=HgQ6uQ6AXOQINImx&_nc_ht=scontent.fcgy2-1.fna&oh=03_AVLnMBYxAa2VSBdLaDwo3xkPROudiBfJbBSRsWcld0NFCA&oe=62B10CA9
![image](https://user-images.githubusercontent.com/105411431/170022210-2a6b76df-966b-4052-860a-d1ea0c711bdf.png)
![image](https://user-images.githubusercontent.com/105411431/170022250-938a9886-83e6-4cfd-9133-78c13b3bc000.png)
![image](https://user-images.githubusercontent.com/105411431/170022272-4eaf16da-6136-4084-9f2a-7f9ed0271ebc.png)

**Comment by MarcPaulBugna** [comment]
guys any reactions, suggestions, recomms para sa icon ta?

**Comment by mariaellahlubat** [comment]
Hi, I have a suggestion regarding sa color ng icon. About sa logo, visually okay na siya pero what if you experiment some color palettes like charcoal-black shades or mattes? Thanks!

**Comment by ChariseAnneDeocos** [comment]
Hi guys! What do think kung ganito ang logo natin?
![CODER_MONKS](https://user-images.githubusercontent.com/99315704/171021682-f7b92c42-6520-4a70-8c25-13c136d53553.png)

**Comment by mariaellahlubat** [comment]
yes puuuu, niceee

**Comment by MarcPaulBugna** [comment]
nice kaayo
