### ISSUE TITLE
Add RESUME function

### ISSUE THREAD

**Issue by mariaellahlubat** [StephenMontenid/EEE100_PROJECT#11]
Hello guys, just want to suggest adding resume button, since wala sa requirements yun ni sir. Mas better rin meron tayo non. Thanks

**Comment by MichelleDescuatan** [comment]
Pwede rin para dagdag features sa stopwatch natin.

**Comment by mariaellahlubat** [comment]
yes beb, what if mag add tayo time and date inside our stopwatch no? Ako nalang mag ppull

**Comment by StephenMontenid** [comment]
Na add ko na guys, try niyo nalang din if gumagana.

**Comment by mariaellahlubat** [comment]
Try ko, sege sege

**Comment by StephenMontenid** [comment]
> yes beb, what if mag add tayo time and date inside our stopwatch no? Ako nalang mag ppull

sige2 ell, gawa nalang ulit new issue para ma discuss nation doon and details.

**Comment by mariaellahlubat** [comment]
Na try ko na yung code, so far wala namang issue.

**Comment by mariaellahlubat** [comment]
Steph, nakalimutan yung module at time import

**Comment by mariaellahlubat** [comment]
Okay na
