### ISSUE TITLE
Digi_clock 

### ISSUE THREAD

**Issue by mariaellahlubat** [StephenMontenid/EEE100_PROJECT#12]
Encoding for digital clock. @MichelleDescuatan beb  @ChariseAnneDeocos since kayo man naga search sa tkinter no, kayo nalang bahala sa design neto. Thank youuu

**Comment by MichelleDescuatan** [comment]
Sige beb noted : > Magupdate lang kami ni @ChariseAnneDeocos .

**Comment by StephenMontenid** [comment]
Ell, na merge ko na pala yung clock.py pero new file pala yon? I add nalang ulit sa source code natin. 

Anyway, makaya ba na gawing 1 line lang yung sa part na i sinet natin yung time? If pwede, try natin para ma optimize natin kahit papano. Yun lang hehe

**Comment by mariaellahlubat** [comment]
close ko na

**Comment by MichelleDescuatan** [comment]
> Encoding for digital clock. @MichelleDescuatan beb @ChariseAnneDeocos since kayo man naga search sa tkinter no, kayo nalang bahala sa design neto. Thank youuu

Beb bale ang design ng digital clock natin ay makita dun sa overall design ng stopwatch natin. Pakicheck na lang kasi inisa ko na lahat. Thank you : >
