### ISSUE TITLE
Stopwatch design

### ISSUE THREAD

**Issue by MichelleDescuatan** [StephenMontenid/EEE100_PROJECT#14]
![RAW](https://user-images.githubusercontent.com/105412257/170818301-15d88df7-0b71-4a75-b7f3-20c866a8a488.png)
Hi guys! Ito na pala yung output natin as of now. Update ko lang kayo kung may idagdag ako. Pwede rin kayo magbigay suggestions. Thank you : >

**Comment by StephenMontenid** [comment]
Nice sige2 mich, i update lang natin dito ulit yung final na output natin.

**Comment by MichelleDescuatan** [comment]
![progress](https://user-images.githubusercontent.com/105412257/170943462-37ca1a75-ae9c-4a5f-b4cd-79ea20eb3eab.JPG)
Hi guys! Ito na pala update design ng stopwatch natin. Bale hinihintay ko na lang si @ChariseAnneDeocos kay may idagdag pa siya. Thank you!

**Comment by StephenMontenid** [comment]
Nicee, malamig sa mata yung user interface \^0^/

**Comment by mariaellahlubat** [comment]
ay bet na siya beb, simple pero hawud ang design ❤️

**Comment by MichelleDescuatan** [comment]
> ay bet na siya beb, simple pero hawud ang design ❤️

Sige sige thank you hehe.

**Comment by ChariseAnneDeocos** [comment]
Hi guys! Take a look at our final design for our stopwatch. I added the save file button on the existing design of @MichelleDescuatan .
![image](https://user-images.githubusercontent.com/99315704/170989181-fefaadb7-225e-413f-8e2f-f20d2552067a.png)

**Comment by ChariseAnneDeocos** [comment]
Final design with logo 
![image](https://user-images.githubusercontent.com/99315704/171022895-14158a4d-de53-40b9-8463-29d40313d427.png)
