### ISSUE TITLE
Keyboard press control function

### ISSUE THREAD

**Issue by StephenMontenid** [StephenMontenid/EEE100_PROJECT#16]
Guys, may i dagdag pala ako na function sa stopwatch natin para sa x-factor na rin. Bale para siyang hotkey. Any thoughts po? suggest lang kayo ng keys for every function like:

start function - spacebar

**Comment by ChariseAnneDeocos** [comment]
Maganda siguro if ang lap is enter key since madali lang maabot aside sa spacebar

**Comment by mariaellahlubat** [comment]
ano, okay na yan sa start button, sa STOP siguro **enter**, sa RESET is **backspace**, di pa ako sure sa ibang buttons hsuhsushu, suggest lang din kayo guys

**Comment by mariaellahlubat** [comment]
okay din yung ka ate @ChariseAnneDeocos  sa lap button, which is **enter**

**Comment by ChariseAnneDeocos** [comment]
mukhang ayos yung backspace key ni @mariaellahlubat para sa **reset**

**Comment by MarcPaulBugna** [comment]
since nakasanayan naman ng pag save file ang ctrl + s. Ctrl + s nalang para sa save?

**Comment by mariaellahlubat** [comment]
Yung hot keys nafinalize na ba natin? Suggest ko sana ito:

   Start/Resumee: spacebar
   Laps: enter
   Reset: backspace
   Stop: shift
   quit: ???

**Comment by StephenMontenid** [comment]
Okay guys noted, regarding sa quit button, parang naga hang sya yung command if ma execute sa latest code natin. Tapos redundant na din siya no? kasi may x button naman. So alisin natin and quit.

Start/ Resume functions= spacebar
Stop function = shift
Lap function = enter
Save file = Ctrl + s

**Comment by mariaellahlubat** [comment]
**nice** sege²
