### ISSUE TITLE
Virtual mouse 

### ISSUE THREAD

**Issue by StephenMontenid** [StephenMontenid/EEE100_PROJECT#17]
Hi guys, may nakita kasi akong idea about image recognition while watching start-up kdrama, tapos madami naman resources na pwedeng basehan, how about we integrate this something like hand-tracking system like another x-factor an rin sana sa stopwatch?
Like we can use our index finger to move through and thumbs-up sign to automatically click the buttons? Parang ganito yung flow feel ko:

Hand recognition -- tracking -- gesture recognition -- execute.

**Comment by mariaellahlubat** [comment]
**wow**, sege² try natiiiin medj maganda.

**Comment by ChariseAnneDeocos** [comment]
hala nice siya, pang x-factor talaga yan

**Comment by mariaellahlubat** [comment]
uhm Steph? Naka decide ka na sa lahat ng hot keys? Kunti lang na suggest namin, hushush.

**Comment by StephenMontenid** [comment]
Check niyo lang yung file guys na upload na. Ty.
