### ISSUE TITLE
Save Design Button

### ISSUE THREAD

**Issue by ChariseAnneDeocos** [StephenMontenid/EEE100_PROJECT#19]
Hi guys! OKaay lang ba ang design sa button? or do you have any suggestions? Thank youu 
![image](https://user-images.githubusercontent.com/99315704/170946946-e62ac267-a974-428a-bfa8-d9695bd3805a.png)

**Comment by MichelleDescuatan** [comment]
What if medyo paliitin ang icon?? Pero kayo hehe okay lang man din siya. @mariaellahlubat @StephenMontenid @MarcPaulBugna ano daw idea niyo guys?

**Comment by mariaellahlubat** [comment]
Kung asa mas bagay bebs,

**Comment by MichelleDescuatan** [comment]
> Hi guys! OKaay lang ba ang design sa button? or do you have any suggestions? Thank youu ![image](https://user-images.githubusercontent.com/99315704/170946946-e62ac267-a974-428a-bfa8-d9695bd3805a.png)

What if ang save button itabi sa file name? Medyo awkward na siya lang isa sa left side hehe. Suggest ko lang tas paliitan konti then walang background color like ang icon lang talaga ang makita hehe.

**Comment by mariaellahlubat** [comment]
Sa save button, mas better if icon lang talaga siya, wala na yung background na paranag border niya. Tapos mas better din if itabi talaga sa file name, I mean between sa space na mag enter ng name sa file sa righ side.

**Comment by MichelleDescuatan** [comment]
> Sa save button, mas better if icon lang talaga siya, wala na yung background na paranag border niya. Tapos mas better din if itabi talaga sa file name, I mean between sa space na mag enter ng name sa file sa righ side.

Yes yes agree!

**Comment by mariaellahlubat** [comment]
Sa baba nga pic ate ang mas bagay

**Comment by StephenMontenid** [comment]
> Saan dito sa dalawa guys? or any suggestions pa ![image](https://user-images.githubusercontent.com/99315704/170956114-2385436d-66ca-4ae1-a2cb-f4717816028d.png) ![image](https://user-images.githubusercontent.com/99315704/170957379-c1d17dcb-a74e-46c6-9eb0-61e566203a7c.png)

Para din sakin, mas ok yung pangalawa hehe

**Comment by StephenMontenid** [comment]
Para din sakin, mas ok yung pangalawa hehe

**Comment by ChariseAnneDeocos** [comment]
Thank you guys sa mga suggestions! Yung pangalawang picture ang final design natin para sa save button.
