### ISSUE TITLE
Library encharge 

### ISSUE THREAD

**Issue by mariaellahlubat** [StephenMontenid/EEE100_PROJECT#8]
Kamo dalawa encharge sa atoang Library nga gamiton, @ChariseAnneDeocos @MichelleDescuatan . Thank you!

**Comment by ChariseAnneDeocos** [comment]
Bali nagsturya nami ni Mich na Tkinter ang gamiton na library

**Comment by MichelleDescuatan** [comment]
Tkinter gamiton nato kay mas dali ug paspas siya maghimo og GUI applications.
